"""
adversarial_bank.py — Banco de contenido para los exámenes adversariales
(x01…x13, ver generate_adversarial.py).

A diferencia de exams.py (pocos exámenes escritos a mano), aquí hay un banco
amplio y variado de preguntas de muchas disciplinas; cada examen adversarial
toma un subconjunto de forma determinista y lo dibuja de una forma pensada
para romper alguna parte del sistema (numeración caótica, dos columnas,
caracteres especiales, marcas distractoras…).

Formato (compacto, se expande en generate_adversarial.py):
  MC     (enunciado, [opciones], índice_correcto)
  MULTI  (enunciado, [opciones], [índices_correctos])
  TF     (enunciado, es_verdadero)
  SA     (enunciado, respuesta)          respuesta corta
  NUM    (enunciado, "número")           respuesta numérica
  ESSAY  enunciado
  MATCH  (enunciado, [(izq, der)...], [distractores_der])
  CLOZE  (texto con {0}{1}, [ ([opciones], [correctas]) ... ])
"""

MC = [
    # ── Geografía e historia ────────────────────────────────────────────────
    ("¿Cuál es la capital de Canadá?", ["Toronto", "Ottawa", "Vancouver", "Montreal"], 1),
    ("¿Qué océano baña las costas occidentales de Chile?", ["Atlántico", "Índico", "Pacífico", "Ártico"], 2),
    ("¿En qué año cayó el Muro de Berlín?", ["1985", "1989", "1991", "1993"], 1),
    ("¿Quién fue el primer presidente de los Estados Unidos?", ["Thomas Jefferson", "John Adams", "George Washington", "Abraham Lincoln"], 2),
    ("¿Cuál es el desierto cálido más extenso del mundo?", ["Gobi", "Sahara", "Kalahari", "Atacama"], 1),
    ("¿Qué civilización construyó Machu Picchu?", ["Maya", "Azteca", "Inca", "Olmeca"], 2),
    ("¿Cuál es el río más caudaloso del mundo?", ["Nilo", "Misisipi", "Amazonas", "Yangtsé"], 2),
    ("¿Qué país tiene forma de bota?", ["España", "Grecia", "Italia", "Portugal"], 2),
    ("La Revolución Francesa comenzó en el año:", ["1776", "1789", "1804", "1815"], 1),
    ("¿Cuál es la montaña más alta del mundo sobre el nivel del mar?", ["K2", "Kilimanjaro", "Everest", "Aconcagua"], 2),
    ("¿Qué estrecho separa Europa de África?", ["Bósforo", "Gibraltar", "Magallanes", "Bering"], 1),
    ("¿Cuál fue la capital del Imperio Romano de Oriente?", ["Atenas", "Alejandría", "Constantinopla", "Antioquía"], 2),
    ("¿Qué país fue gobernado por los faraones?", ["Mesopotamia", "Egipto", "Persia", "Fenicia"], 1),
    ("¿En qué continente se encuentra Mongolia?", ["Europa", "Asia", "África", "Oceanía"], 1),
    ("La Segunda Guerra Mundial terminó en:", ["1943", "1945", "1947", "1950"], 1),
    ("¿Cuál es el lago navegable más alto del mundo?", ["Titicaca", "Victoria", "Baikal", "Superior"], 0),
    ("¿Qué tratado dividió el Nuevo Mundo entre España y Portugal en 1494?", ["Versalles", "Tordesillas", "Utrecht", "Westfalia"], 1),
    ("¿Cuál es la moneda oficial de Japón?", ["Won", "Yuan", "Yen", "Ringgit"], 2),
    ("¿Qué isla es la más grande del mundo?", ["Madagascar", "Groenlandia", "Borneo", "Nueva Guinea"], 1),
    ("¿Quién pintó La noche estrellada?", ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí"], 1),
    # ── Ciencias ────────────────────────────────────────────────────────────
    ("¿Cuál es el elemento químico con número atómico 6?", ["Oxígeno", "Carbono", "Nitrógeno", "Boro"], 1),
    ("¿Qué organelo celular produce la mayor parte del ATP?", ["Ribosoma", "Mitocondria", "Lisosoma", "Núcleo"], 1),
    ("¿Cuál es la velocidad aproximada de la luz en el vacío?", ["300 000 km/s", "150 000 km/s", "30 000 km/s", "3 000 000 km/s"], 0),
    ("¿Qué gas compone la mayor parte de la atmósfera terrestre?", ["Oxígeno", "Nitrógeno", "Argón", "Dióxido de carbono"], 1),
    ("¿Qué vitamina se sintetiza en la piel con la luz solar?", ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina K"], 2),
    ("La primera ley de Newton también se conoce como ley de:", ["acción y reacción", "inercia", "gravitación", "conservación de la energía"], 1),
    ("¿Cuál es el pH de una solución neutra a 25 °C?", ["0", "7", "10", "14"], 1),
    ("¿Qué tipo de enlace comparte electrones entre átomos?", ["Iónico", "Covalente", "Metálico", "De hidrógeno"], 1),
    ("¿Cuántos cromosomas tiene una célula humana somática normal?", ["23", "44", "46", "48"], 2),
    ("¿Qué planeta tiene los anillos más visibles?", ["Júpiter", "Saturno", "Urano", "Neptuno"], 1),
    ("¿Qué partícula tiene carga eléctrica negativa?", ["Protón", "Neutrón", "Electrón", "Fotón"], 2),
    ("¿Cuál es la unidad de la resistencia eléctrica?", ["Voltio", "Amperio", "Ohmio", "Vatio"], 2),
    ("La fotosíntesis ocurre principalmente en los:", ["cloroplastos", "ribosomas", "vacuolas", "centriolos"], 0),
    ("¿Qué científico propuso la teoría de la evolución por selección natural?", ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Alexander Fleming"], 1),
    ("¿Cuál es el punto de ebullición del agua a 1 atm en la escala Kelvin?", ["273 K", "323 K", "373 K", "473 K"], 2),
    ("¿Qué órgano filtra la sangre y produce la orina?", ["Hígado", "Riñón", "Bazo", "Páncreas"], 1),
    ("¿Qué tipo de roca se forma por enfriamiento del magma?", ["Sedimentaria", "Metamórfica", "Ígnea", "Detrítica"], 2),
    ("¿Qué mide un sismógrafo?", ["La presión atmosférica", "Las vibraciones del suelo", "La humedad", "La radiación solar"], 1),
    ("¿Cuál es el hueso más largo del cuerpo humano?", ["Húmero", "Tibia", "Fémur", "Peroné"], 2),
    ("La fórmula química del agua oxigenada es:", ["H2O", "H2O2", "HO2", "OH"], 1),
    ("¿Qué grupo sanguíneo se considera donante universal?", ["A+", "AB+", "O−", "B−"], 2),
    ("¿Cuál es la energía que posee un cuerpo por su movimiento?", ["Potencial", "Cinética", "Térmica", "Química"], 1),
    ("¿Qué estructura de la célula vegetal no existe en la célula animal?", ["Membrana plasmática", "Pared celular", "Núcleo", "Citoplasma"], 1),
    ("¿Cuál es el metal líquido a temperatura ambiente?", ["Plomo", "Mercurio", "Estaño", "Cobre"], 1),
    ("¿Qué galaxia contiene a nuestro sistema solar?", ["Andrómeda", "Vía Láctea", "Triángulo", "Sombrero"], 1),
    # ── Matemáticas ─────────────────────────────────────────────────────────
    ("¿Cuál es la derivada de x²?", ["x", "2x", "x²", "2"], 1),
    ("¿Cuánto vale la raíz cuadrada de 144?", ["10", "11", "12", "14"], 2),
    ("¿Cuál es el valor de pi con dos decimales?", ["3,12", "3,14", "3,16", "3,18"], 1),
    ("La suma de los ángulos internos de un triángulo es:", ["90°", "180°", "270°", "360°"], 1),
    ("¿Cuál de estos números es primo?", ["21", "27", "29", "33"], 2),
    ("¿Cuál es el resultado de 2³ + 3²?", ["13", "17", "15", "12"], 1),
    ("¿Cuántas diagonales tiene un cuadrilátero?", ["1", "2", "3", "4"], 1),
    ("Si f(x) = 3x + 2, ¿cuánto vale f(4)?", ["12", "14", "16", "10"], 1),
    ("¿Cuál es el mínimo común múltiplo de 4 y 6?", ["6", "12", "18", "24"], 1),
    ("¿Qué porcentaje es 45 de 180?", ["20 %", "25 %", "30 %", "35 %"], 1),
    ("¿Cuál es el área de un círculo de radio 3 (en función de pi)?", ["6 pi", "9 pi", "3 pi", "12 pi"], 1),
    ("¿Cuál es la mediana del conjunto {3, 9, 4, 7, 5}?", ["4", "5", "6", "7"], 1),
    # ── Programación e informática ─────────────────────────────────────────
    ("¿Qué palabra reservada define una función en Python?", ["func", "def", "function", "fn"], 1),
    ("¿Qué imprime print(len([1, 2, 3]))?", ["2", "3", "4", "Error"], 1),
    ("¿Qué estructura de datos funciona con el principio LIFO?", ["Cola", "Pila", "Árbol", "Grafo"], 1),
    ("¿Qué significa la sigla SQL?", ["Structured Query Language", "Simple Question List", "System Query Logic", "Standard Quick Language"], 0),
    ("¿Cuál es la complejidad de la búsqueda binaria?", ["O(n)", "O(log n)", "O(n²)", "O(1)"], 1),
    ("¿Qué protocolo se usa para transferir páginas web de forma segura?", ["FTP", "HTTPS", "SMTP", "SSH"], 1),
    ("¿Qué operador de Python realiza la división entera?", ["/", "//", "%", "**"], 1),
    ("En Git, ¿qué comando crea una copia local de un repositorio remoto?", ["git pull", "git clone", "git fetch", "git init"], 1),
    ("¿Qué representa la sigla CPU?", ["Central Processing Unit", "Computer Personal Unit", "Core Power Utility", "Central Program Update"], 0),
    ("¿Cuál de estos es un lenguaje de marcado?", ["Python", "HTML", "C++", "Rust"], 1),
    ("¿Qué código de estado HTTP indica que un recurso no fue encontrado?", ["200", "301", "404", "500"], 2),
    ("¿Qué tipo de dato usa Python para pares clave-valor?", ["list", "tuple", "dict", "set"], 2),
    ("¿Cuántos bits tiene un byte?", ["4", "8", "16", "32"], 1),
    ("¿Cuál es el resultado de 7 % 3 en Python?", ["1", "2", "0", "3"], 0),
    ("¿Qué comando de SQL elimina las filas que cumplen una condición?", ["DROP", "DELETE", "REMOVE", "ERASE"], 1),
    ("¿Qué es una clave primaria en una base de datos relacional?", ["Un campo que identifica de forma única cada registro", "Una contraseña del administrador", "Un índice de texto completo", "Una copia de seguridad"], 0),
    ("¿Qué algoritmo de ordenamiento tiene complejidad promedio O(n log n)?", ["Burbuja", "Inserción", "Quicksort", "Selección"], 2),
    ("¿Qué método de HTTP se usa normalmente para crear un recurso?", ["GET", "POST", "HEAD", "TRACE"], 1),
    ("¿Qué imprime print('a' * 3)?", ["a3", "aaa", "3a", "Error"], 1),
    ("¿Qué capa del modelo OSI se encarga del enrutamiento?", ["Enlace de datos", "Red", "Transporte", "Sesión"], 1),
    ("¿Qué extensión suelen tener los archivos de hojas de estilo?", [".css", ".html", ".js", ".xml"], 0),
    ("¿Qué hace la instrucción break dentro de un bucle?", ["Salta a la siguiente iteración", "Termina el bucle", "Reinicia el bucle", "Lanza una excepción"], 1),
    ("¿Qué es el kernel de un sistema operativo?", ["El núcleo que gestiona los recursos del hardware", "Un editor de texto", "Un antivirus", "Un navegador"], 0),
    ("¿Cuál es el sistema de numeración en base 2?", ["Octal", "Decimal", "Binario", "Hexadecimal"], 2),
    ("¿Qué estructura de control ejecuta código solo si se cumple una condición?", ["for", "while", "if", "import"], 2),
    # ── Lengua, humanidades, economía, derecho, salud ──────────────────────
    ("¿Cuál es el sinónimo de «efímero»?", ["Duradero", "Pasajero", "Eterno", "Sólido"], 1),
    ("¿Qué figura literaria compara dos elementos usando «como»?", ["Metáfora", "Símil", "Hipérbole", "Ironía"], 1),
    ("¿Quién escribió Cien años de soledad?", ["Mario Vargas Llosa", "Gabriel García Márquez", "Julio Cortázar", "Jorge Luis Borges"], 1),
    ("¿Cuál de estas palabras es aguda?", ["Árbol", "Canción", "Lápiz", "Útil"], 1),
    ("¿Qué es el PIB?", ["El valor total de los bienes y servicios producidos en un país en un periodo", "El total de impuestos recaudados", "La deuda externa de un país", "El número de empleados de un país"], 0),
    ("¿Qué ocurre con el precio cuando la demanda aumenta y la oferta se mantiene?", ["Baja", "Sube", "Se mantiene", "Desaparece"], 1),
    ("¿Qué es la inflación?", ["Aumento generalizado y sostenido de los precios", "Disminución del desempleo", "Aumento de las exportaciones", "Caída del tipo de cambio únicamente"], 0),
    ("En derecho, ¿qué significa «habeas corpus»?", ["Derecho a la propiedad", "Protección contra la detención arbitraria", "Derecho de autor", "Libertad de prensa"], 1),
    ("¿Qué vitamina previene el escorbuto?", ["Vitamina B12", "Vitamina C", "Vitamina E", "Vitamina A"], 1),
    ("¿Qué corriente artística pintó relojes derretidos?", ["Cubismo", "Surrealismo", "Impresionismo", "Barroco"], 1),
    ("¿Quién compuso la Novena Sinfonía?", ["Mozart", "Beethoven", "Bach", "Chopin"], 1),
    ("¿Qué es un adjetivo?", ["Una palabra que modifica al sustantivo", "Una palabra que expresa acción", "Una palabra que sustituye al nombre", "Una palabra que enlaza oraciones"], 0),
    ("¿Cuál es el plural de «lápiz»?", ["lápizes", "lápices", "lápiz", "lápizs"], 1),
    ("¿Qué es la mitosis?", ["División celular que produce dos células idénticas", "Formación de gametos", "Muerte celular programada", "Fusión de dos células"], 0),
    ("¿Qué órgano regula el nivel de glucosa mediante la insulina?", ["Hígado", "Páncreas", "Riñón", "Bazo"], 1),
    ("¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?", ["1776", "1789", "1812", "1492"], 0),
    ("¿Qué es un monopolio?", ["Mercado con un único vendedor", "Mercado con muchos vendedores", "Mercado sin compradores", "Mercado regulado por sus consumidores"], 0),
    ("¿Qué tipo de texto tiene como finalidad convencer al lector?", ["Narrativo", "Argumentativo", "Descriptivo", "Instructivo"], 1),
    ("¿Cuál es la capital de Australia?", ["Sídney", "Melbourne", "Canberra", "Perth"], 2),
    ("¿Cuál de estos es un mamífero marino?", ["Tiburón", "Delfín", "Atún", "Pulpo"], 1),
    ("¿Qué es el ADN?", ["Ácido desoxirribonucleico, portador de la información genética", "Una proteína estructural", "Un tipo de azúcar", "Una hormona"], 0),
    ("¿Qué elemento es el más abundante en el universo?", ["Oxígeno", "Helio", "Hidrógeno", "Carbono"], 2),
    ("¿Cuál es el país más poblado de Sudamérica?", ["Argentina", "Colombia", "Brasil", "Perú"], 2),
    ("¿Cómo se llama la línea imaginaria que divide la Tierra en hemisferio norte y sur?", ["Meridiano de Greenwich", "Ecuador", "Trópico de Cáncer", "Círculo polar"], 1),
    ("¿Qué estructura protege al cerebro?", ["Costillas", "Cráneo", "Pelvis", "Columna"], 1),
]

MULTI = [
    ("Selecciona todos los números primos:", ["2", "9", "11", "15", "17"], [0, 2, 4]),
    ("¿Cuáles de estos animales son mamíferos?", ["Ballena", "Tiburón", "Murciélago", "Pingüino", "Delfín"], [0, 2, 4]),
    ("Selecciona los lenguajes de programación:", ["Python", "HTML", "Java", "CSS", "Go"], [0, 2, 4]),
    ("¿Cuáles de estos países están en Sudamérica?", ["Bolivia", "Guatemala", "Uruguay", "Cuba", "Paraguay"], [0, 2, 4]),
    ("¿Cuáles son estados de la materia comunes?", ["Sólido", "Líquido", "Metálico", "Gaseoso"], [0, 1, 3]),
    ("Marca las afirmaciones correctas sobre la fotosíntesis:", ["Produce oxígeno", "Ocurre en las mitocondrias", "Usa luz solar", "Consume dióxido de carbono"], [0, 2, 3]),
    ("¿Cuáles de estos son métodos HTTP?", ["GET", "FETCH", "POST", "PUSH", "DELETE"], [0, 2, 4]),
    ("¿Cuáles de estas figuras tienen cuatro lados?", ["Cuadrado", "Triángulo", "Rombo", "Pentágono"], [0, 2]),
    ("Selecciona los colores primarios en pigmento (modelo tradicional):", ["Rojo", "Verde", "Azul", "Amarillo"], [0, 2, 3]),
    ("¿Cuáles de estos son tipos de datos primitivos en Java?", ["int", "String", "boolean", "double", "List"], [0, 2, 3]),
    ("¿Cuáles son ejemplos de energías renovables?", ["Solar", "Carbón", "Eólica", "Petróleo", "Hidráulica"], [0, 2, 4]),
    ("Elige los escritores latinoamericanos:", ["Gabriela Mistral", "William Shakespeare", "Pablo Neruda", "Miguel de Cervantes"], [0, 2]),
]

TF = [
    ("El Sol es una estrella.", True),
    ("Los delfines son peces.", False),
    ("El número 0 es par.", True),
    ("La Gran Muralla China es visible a simple vista desde el espacio.", False),
    ("En Python, las listas son mutables.", True),
    ("El agua está compuesta por hidrógeno y oxígeno.", True),
    ("Australia es un continente y un país a la vez.", True),
    ("El corazón humano tiene cuatro cavidades.", True),
    ("La luz viaja más lento que el sonido.", False),
    ("Un byte equivale a 4 bits.", False),
    ("HTTP es un protocolo sin estado.", True),
    ("La ciudad de Estambul se encuentra en dos continentes.", True),
    ("El oro es un metal más ligero que el agua.", False),
    ("La mitocondria es la central energética de la célula.", True),
    ("Los hongos pertenecen al reino vegetal.", False),
    ("La raíz cuadrada de 49 es 6.", False),
    ("Un átomo neutro tiene igual número de protones y electrones.", True),
    ("Júpiter es el planeta más cercano al Sol.", False),
    ("El español es el idioma oficial de Brasil.", False),
    ("La capital de Perú es Lima.", True),
    ("El ADN se encuentra únicamente en las células vegetales.", False),
    ("El código binario usa únicamente los dígitos 0 y 1.", True),
    ("La Primera Guerra Mundial comenzó en 1914.", True),
    ("Un ángulo de 90 grados se llama agudo.", False),
    ("SQL se usa para consultar bases de datos relacionales.", True),
    ("El metano es un gas de efecto invernadero.", True),
    ("Los reptiles son animales de sangre caliente.", False),
    ("La Revolución Industrial comenzó en Inglaterra.", True),
    ("El punto de congelación del agua es 100 °C.", False),
    ("Un ciclo while puede no ejecutarse ninguna vez.", True),
    ("El río Amazonas desemboca en el océano Pacífico.", False),
    ("La fracción 3/6 es equivalente a 1/2.", True),
    ("La inflación es la disminución generalizada de los precios.", False),
    ("Mozart fue un compositor del periodo clásico.", True),
    ("El ozono protege de la radiación ultravioleta.", True),
    ("La Tierra tarda unos 365 días en orbitar el Sol.", True),
    ("El plural de «pez» es «pezes».", False),
]

SA = [
    ("¿Cómo se llama el proceso por el cual las plantas producen su alimento con luz?", "Fotosíntesis"),
    ("¿Cuál es el símbolo químico del sodio?", "Na"),
    ("¿Cómo se llama el lenguaje que estructura las páginas web?", "HTML"),
    ("¿Qué figura geométrica tiene tres lados?", "Triángulo"),
    ("¿Cuál es el nombre del satélite natural de la Tierra?", "Luna"),
    ("¿Cuál es la capital de Argentina?", "Buenos Aires"),
    ("¿Qué gas necesitan los seres humanos para respirar?", "Oxígeno"),
    ("¿Cómo se llama la división de una célula en dos células idénticas?", "Mitosis"),
    ("¿Quién escribió El Quijote?", "Cervantes"),
    ("¿Qué instrumento mide la temperatura?", "Termómetro"),
    ("¿Cómo se llama la estructura de datos que sigue el principio FIFO?", "Cola"),
    ("¿Cómo se llama el hueso del muslo?", "Fémur"),
    ("¿Cómo se llama el paso de un líquido a gas?", "Evaporación"),
    ("¿Cuál es la unidad de la fuerza en el Sistema Internacional?", "Newton"),
    ("¿Cómo se llama el órgano que bombea la sangre?", "Corazón"),
    ("¿Qué lenguaje de consulta se usa en las bases de datos relacionales?", "SQL"),
]

NUM = [
    ("¿Cuántos minutos hay en tres horas?", "180"),
    ("¿Cuánto es 15 × 14?", "210"),
    ("¿Cuál es la raíz cuadrada de 225?", "15"),
    ("¿Cuántos grados tiene un ángulo recto?", "90"),
    ("Un tren recorre 240 km en 3 horas. ¿Cuál es su velocidad media en km/h?", "80"),
    ("¿Cuánto es 7,5 + 2,25?", "9,75"),
    ("¿Cuánto es 3 − 8?", "-5"),
    ("¿Cuántos lados tiene un dodecágono?", "12"),
    ("¿Cuántos segundos hay en 5 minutos?", "300"),
    ("¿Cuánto es el 20 % de 350?", "70"),
    ("¿Cuál es el perímetro, en cm, de un cuadrado de lado 6,5 cm?", "26"),
    ("¿Cuántos bits hay en 4 bytes?", "32"),
    ("¿Cuál es el resultado de 2 elevado a la 10?", "1024"),
    ("Si 5 kg de manzanas cuestan 20 dólares, ¿cuántos dólares cuestan 8 kg?", "32"),
]

ESSAY = [
    "Explica con tus palabras las causas de la Primera Guerra Mundial.",
    "Describe el ciclo del agua y su importancia para los ecosistemas.",
    "Analiza las ventajas y desventajas del uso de energías renovables.",
    "Desarrolla una opinión fundamentada sobre el impacto de las redes sociales en los adolescentes.",
    "Explica la diferencia entre una pila y una cola y da un ejemplo de uso de cada una.",
    "Describe las fases de la mitosis.",
    "Comenta las consecuencias económicas de una inflación sostenida.",
    "Explica qué es la normalización en bases de datos y por qué es útil.",
    "Redacta un párrafo argumentativo sobre la importancia de la lectura.",
    "Analiza el papel de la Revolución Industrial en el crecimiento de las ciudades.",
    "Describe cómo funciona el protocolo HTTP en una petición típica.",
    "Discute las implicaciones éticas del uso de inteligencia artificial en la educación.",
    "Explica el concepto de oferta y demanda con un ejemplo cotidiano.",
]

MATCH = [
    ("Relaciona cada país con su capital.",
     [("Perú", "Lima"), ("Chile", "Santiago"), ("Brasil", "Brasilia"), ("Argentina", "Buenos Aires"),
      ("Uruguay", "Montevideo"), ("Bolivia", "Sucre")], []),
    ("Relaciona cada elemento químico con su símbolo.",
     [("Oro", "Au"), ("Plata", "Ag"), ("Hierro", "Fe"), ("Sodio", "Na"), ("Potasio", "K")], ["Pb"]),
    ("Relaciona cada científico con su aporte.",
     [("Newton", "Ley de la gravitación universal"), ("Darwin", "Selección natural"),
      ("Pasteur", "Pasteurización y vacunas"), ("Curie", "Estudios sobre la radiactividad"),
      ("Mendel", "Leyes de la herencia")], ["Teoría de la relatividad"]),
    ("Relaciona cada autor con su obra.",
     [("Cervantes", "Don Quijote de la Mancha"), ("García Márquez", "Cien años de soledad"),
      ("Neruda", "Veinte poemas de amor y una canción desesperada"), ("Borges", "El Aleph"),
      ("Cortázar", "Rayuela")], []),
    ("Relaciona cada término informático con su definición.",
     [("RAM", "Memoria volátil de acceso aleatorio"), ("CPU", "Unidad que ejecuta las instrucciones"),
      ("SSD", "Almacenamiento sin partes móviles"), ("GPU", "Procesador especializado en gráficos"),
      ("BIOS", "Firmware que inicia el equipo")], ["Sistema de archivos"]),
    ("Relaciona cada órgano con su función principal.",
     [("Pulmón", "Intercambio de gases"), ("Riñón", "Filtrado de la sangre"), ("Corazón", "Bombeo de sangre"),
      ("Hígado", "Metabolismo y desintoxicación"), ("Estómago", "Digestión inicial de los alimentos")], []),
    ("Relaciona cada palabra con su sinónimo.",
     [("Efímero", "Pasajero"), ("Locuaz", "Hablador"), ("Prístino", "Original"), ("Ubérrimo", "Abundante")],
     ["Silencioso", "Oscuro"]),
    ("Relaciona cada unidad con la magnitud que mide.",
     [("Newton", "Fuerza"), ("Julio", "Energía"), ("Vatio", "Potencia"), ("Pascal", "Presión"),
      ("Hercio", "Frecuencia"), ("Ohmio", "Resistencia eléctrica")], []),
    ("Relaciona cada evento con su año.",
     [("Caída del Muro de Berlín", "1989"), ("Llegada de Colón a América", "1492"),
      ("Inicio de la Revolución Francesa", "1789"), ("Fin de la Segunda Guerra Mundial", "1945")],
     ["1066", "1917"]),
    ("Relaciona cada protocolo con su uso.",
     [("HTTP", "Transferencia de páginas web"), ("SMTP", "Envío de correo electrónico"),
      ("FTP", "Transferencia de archivos"), ("DNS", "Resolución de nombres de dominio"),
      ("SSH", "Acceso remoto seguro")], []),
    ("Relaciona cada vitamina con su función.",
     [("Vitamina C", "Previene el escorbuto"), ("Vitamina D", "Favorece la absorción de calcio"),
      ("Vitamina K", "Participa en la coagulación"), ("Vitamina A", "Salud de la visión")], ["Producción de insulina"]),
    ("Relaciona cada lenguaje con su ámbito habitual de uso.",
     [("JavaScript", "Interactividad en navegadores"), ("SQL", "Consultas a bases de datos"),
      ("CSS", "Presentación de páginas web"), ("Bash", "Automatización en la terminal")], []),
    ("Relaciona cada figura geométrica con su número de lados.",
     [("Triángulo", "3"), ("Cuadrilátero", "4"), ("Pentágono", "5"), ("Hexágono", "6"), ("Octógono", "8")], []),
]

CLOZE = [
    ("La capital de Francia es {0} y su río principal es el {1}.",
     [(["París", "Lyon", "Marsella"], [0]), (["Sena", "Loira", "Ródano"], [0])]),
    ("El proceso por el cual las plantas fabrican su alimento se llama {0}.",
     [(["fotosíntesis", "respiración", "digestión"], [0])]),
    ("En un triángulo rectángulo, el lado opuesto al ángulo recto se llama {0}, y el teorema de {1} relaciona sus lados.",
     [(["hipotenusa", "cateto", "apotema"], [0]), (["Tales", "Pitágoras", "Euclides"], [1])]),
    ("El {0} es el planeta más grande del sistema solar y {1} es el más cercano al Sol.",
     [(["Júpiter", "Saturno", "Neptuno"], [0]), (["Mercurio", "Venus", "Marte"], [0])]),
    ("Los seres vivos que producen su propio alimento se denominan {0}.",
     [(["autótrofos", "heterótrofos", "descomponedores"], [0])]),
    ("En Python, una {0} es una colección ordenada y mutable, mientras que una {1} es inmutable.",
     [(["lista", "tupla", "cadena"], [0]), (["tupla", "lista", "diccionario"], [0])]),
    ("La Revolución Francesa comenzó en {0} y el lema de la República era «libertad, igualdad y {1}».",
     [(["1789", "1799", "1815"], [0]), (["fraternidad", "justicia", "unidad"], [0])]),
    ("El {0} es el órgano que bombea la sangre y los {1} son los vasos que la llevan de vuelta al corazón.",
     [(["corazón", "hígado", "pulmón"], [0]), (["venas", "arterias", "capilares"], [0])]),
    ("La molécula de agua está formada por {0} átomos de hidrógeno y {1} de oxígeno.",
     [(["dos", "tres", "uno"], [0]), (["uno", "dos", "tres"], [0])]),
    ("Los colores primarios de la luz son {0}, {1} y {2}.",
     [(["rojo", "amarillo", "magenta"], [0]), (["verde", "naranja", "cian"], [0]), (["azul", "violeta", "marrón"], [0])]),
    ("La sigla HTTP significa {0} Transfer {1}.",
     [(["Hypertext", "Hyperlink", "Hardware"], [0]), (["Protocol", "Program", "Process"], [0])]),
    ("Los mamíferos que vuelan son los {0}; los que viven en el mar y respiran aire son los {1}.",
     [(["murciélagos", "pájaros", "insectos"], [0]), (["cetáceos", "peces", "moluscos"], [0])]),
    ("El escritor {0} recibió el Premio Nobel de Literatura en 1982 por {1}.",
     [(["Gabriel García Márquez", "Pablo Neruda", "Octavio Paz"], [0]), (["Cien años de soledad", "Rayuela", "Ficciones"], [0])]),
    ("La ley de la oferta y la demanda afirma que si la demanda {0} y la oferta se mantiene, el precio {1}.",
     [(["aumenta", "disminuye", "desaparece"], [0]), (["sube", "baja", "se congela"], [0])]),
    ("En una base de datos relacional, cada tabla se compone de {0} y {1}.",
     [(["filas", "capas", "nodos"], [0]), (["columnas", "carpetas", "índices"], [0])]),
    ("Un año bisiesto tiene {0} días y el día extra se agrega en el mes de {1}.",
     [(["366", "365", "364"], [0]), (["febrero", "enero", "diciembre"], [0])]),
]

# Párrafo de lectura para x06 (preguntas que dependen de un texto previo).
PASAJE = (
    "La ciudad de Tikal, en el actual territorio de Guatemala, fue uno de los centros urbanos más "
    "importantes de la civilización maya. Alcanzó su máximo esplendor entre los siglos III y IX, "
    "cuando llegó a albergar decenas de miles de habitantes. Sus templos piramidales, como el "
    "Templo del Gran Jaguar, se elevan por encima de la selva y servían tanto para ceremonias "
    "religiosas como para honrar a los gobernantes. Hacia el año 900 la ciudad fue abandonada de "
    "forma gradual; los investigadores atribuyen el colapso a una combinación de sequías, guerras "
    "y agotamiento de los recursos."
)
PASAJE_QS = [
    ("Según el texto, ¿en qué país se encuentra actualmente Tikal?", ["México", "Guatemala", "Honduras", "Belice"], 1),
    ("Según el texto, ¿qué función tenían los templos piramidales?", [
        "Almacenar alimentos", "Servir como fortalezas militares",
        "Realizar ceremonias religiosas y honrar a los gobernantes", "Observar el clima"], 2),
    ("De acuerdo con el texto, ¿entre qué siglos alcanzó Tikal su máximo esplendor?", [
        "Entre los siglos I y III", "Entre los siglos III y IX", "Entre los siglos IX y XV", "Entre los siglos XV y XVIII"], 1),
    ("Según el texto, ¿cuál se considera una causa del colapso de la ciudad?", [
        "Un terremoto único", "La llegada de los conquistadores en el año 900",
        "Una combinación de sequías, guerras y agotamiento de recursos", "Una epidemia de origen desconocido"], 2),
]
